RMarket.WebUI/Controllers/EntityParamsController.cs
using RMarket.ClassLib.Abstract;
using RMarket.ClassLib.Abstract.IRepository;
using RMarket.ClassLib.Entities;
using RMarket.ClassLib.Helpers;
using RMarket.ClassLib.Helpers.Extentions;
using RMarket.ClassLib.Infrastructure.AmbientContext;
using RMarket.ClassLib.Models;
using RMarket.WebUI.Models;
using RMarket.WebUI.Models.ParamforEdit;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMarket.WebUI.Controllers
{
    public class EntityParamsController : Controller
    {
        private readonly IEntityInfoRepository entityInfoRepository;
        private readonly IResolver resolver;

        public MyMapper Mapper { get; set; }

        public EntityParamsController(IEntityInfoRepository entityInfoRepository, IResolver resolver)
        {
            this.entityInfoRepository = entityInfoRepository;
            this.resolver = resolver;
        }

        //Новый экземпляр
        public PartialViewResult EditParamsNew(int entityInfoId)
        {
            EntityInfo entityInfo = entityInfoRepository.GetById(entityInfoId);
            object entity = resolver.Resolve<object>(Type.GetType(entityInfo.TypeName));
            IEnumerable<ParamEntity> entityParams = new SettingHelper().GetEntityParams<ParamEntity>(entity);

            //Конвертим параметры в UI модель
            IEnumerable<ParamEntityUI> entityParamsUI = Mapper
                .Map<IEnumerable<ParamEntity>, IEnumerable<ParamEntityUI>>(entityParams);

            return PartialView("EditParams", entityParamsUI);
        }

        /// <summary>
        /// Частичное представление выводит значение параметра с атрибутом ParameterAttribute
        /// </summary>
        /// <param name="paramEntityEdit">ключ - имя элемента</param>
        /// <returns></returns>
        public PartialViewResult EditorForObject(ParamEntityEditForObject paramEntityEdit)
        {
            // разные вью на разные типы значений
            object originValue = paramEntityEdit.ParamEntityUI.OriginValue;

            if (originValue is bool)
                return PartialView("EditorForBool", paramEntityEdit);
            else if (originValue is IEnumerable && !(originValue is string))
                return PartialView("EditorForCollection", paramEntityEdit);
            else if (originValue is Enum)
            {
                return EditForEnum(paramEntityEdit);
            }
            else
                return PartialView(paramEntityEdit);

        }

        public string GetDesctiptionForEnum(string enumValue, string typeName)
        {
            Type type = Type.GetType(typeName);
            var value = Enum.Parse(type, enumValue);
            return ((Enum)value).Description();
        }

        private PartialViewResult EditForEnum(ParamEntityEditForObject paramEntityEdit)
        {
            object originValue = paramEntityEdit.ParamEntityUI.OriginValue;

            var enumValues = Enum.GetValues(originValue.GetType());
            var enumValuesSelectList = new List<SelectListItem>();
            var listDescriptions = new List<SelectListItem>();
            foreach (var enumValue in enumValues)
            {
                enumValuesSelectList.Add(new SelectListItem
                {
                    Value = ((Enum)enumValue).ToString("F"),
                    Text = ((Enum)enumValue).Name(),
                    Selected = enumValue.ToString() == originValue.ToString()
                });

                listDescriptions.Add(new SelectListItem
                {
                    Value = ((Enum)enumValue).ToString("F"),
                    Text = ((Enum)enumValue).Description(),
                    Selected = enumValue == originValue
                });
            }

            var model = new ParamEntityUiForEnum
            {
                ControlId = paramEntityEdit.ControlId,
                ParamEntityUI = paramEntityEdit.ParamEntityUI,
                ValuesSelectList = enumValuesSelectList,
                //DescriptionCollection = listDescriptions
            };

            return PartialView("EditorForEnum", model);
        }
    }
}

RMarket.WebUI/Controllers/InstanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using RMarket.ClassLib.Abstract;
using RMarket.ClassLib.Entities;
using RMarket.ClassLib.Models;
using RMarket.WebUI.Infrastructure;
using RMarket.ClassLib.Helpers;
using RMarket.WebUI.Models;
using RMarket.ClassLib.EntityModels;
using RMarket.ClassLib.Abstract.IService;
using RMarket.ClassLib.Abstract.IRepository;
using RMarket.ClassLib.Infrastructure.AmbientContext;

namespace RMarket.WebUI.Controllers
{
    public class InstanceController : Controller
    {
        private IInstanceService instanceService;
        private ITickerRepository tickerRepository;
        private ITimeFrameRepository timeFrameRepository;
        private IEntityInfoRepository entityInfoRepository;
        private readonly IResolver resolver;

        public MyMapper Mapper { get; set; }

        public InstanceController(IInstanceService instanceService, ITickerRepository tickerRepository, ITimeFrameRepository timeFrameRepository, IEntityInfoRepository entityInfoRepository, IResolver resolver)
        {
            this.instanceService = instanceService;
            this.tickerRepository = tickerRepository;
            this.timeFrameRepository = timeFrameRepository;
            this.entityInfoRepository = entityInfoRepository;
            this.resolver = resolver;
        }

        /// <summary>
        /// Список вариантов стратегий
        /// </summary>
        /// <returns></returns>
        public ViewResult Index(int entityInfoId = 0)
        {
            IEnumerable<InstanceModel> res = instanceService.Get(T => T
                .Where(i => i.EntityInfoId == entityInfoId || entityInfoId == 0)
                .GroupBy(s => s.GroupID)
                .SelectMany(g => g.Select(s => s)
                    .OrderByDescending(s => s.Id)
                    .Take(1)
                ).Include(m => m.EntityInfo)
            );

            return View(res);

        }

        /// <summary>
        /// Редактирование стратегии
        /// </summary>
        /// <param name="id">Если 0 - создание нвого варианта</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Edit(int id = 0)
        {
            InitializeLists();
            InstanceModel model = null;

            if (id != 0)
            {
                model = instanceService.GetById(id, true);
                if (model == null)
                {
                    TempData["error"] = String.Format("Экземпляр стратегии \"{0}\"  не найден!", id);
                    return RedirectToAction("Index");
                }
                RepairParams(model);
            }
            else 
                model = new InstanceModel();

            InstanceModelUI modelUI = Mapper
                .Map<InstanceModel, InstanceModelUI>(model);

            return View("Edit", modelUI);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(InstanceModelUI modelUI, IEnumerable<ParamEntityUI> strategyParams)
        {
            modelUI.EntityParams = strategyParams.ToList();

            if (ModelState.IsValid)
            {
                //Сохранение
                InstanceModel model = Mapper
                    .Map<InstanceModelUI, InstanceModel>(modelUI);

                instanceService.Save(model);

                TempData["message"] = String.Format("Сохранены изменения в экземпляре: {0}", model.Name);
                return RedirectToAction("Index");
            }

            else
            {
                return _Edit(modelUI);
            }

        }

        [HttpGet]
        public ActionResult Copy(int id)
        {
            InstanceModel model = instanceService.GetById(id, true);
            if (model == null)
            {
                TempData["error"] = String.Format("Экземпляр стратегии \"{0}\"  не найден!", id);
                return RedirectToAction("Index");
            }
            RepairParams(model);

            model.Id = 0;

            InstanceModelUI modelUI = Mapper
                .Map<InstanceModel, InstanceModelUI>(model);

            return _Edit(modelUI);
        }

        public ActionResult Details(int id)
        {
            InstanceModel model = new InstanceModel();
            if (id != 0)
            {
                model = instanceService.GetById(id, true);
                if (model == null)
                {
                    TempData["error"] = String.Format("Экземпляр стратегии \"{0}\"  не найден!", id);
                    return RedirectToAction("Index");
                }
                RepairParams(model);
            }

            InstanceModelUI modelUI = Mapper
                .Map<InstanceModel, InstanceModelUI>(model);

            return View(modelUI);
        }

        public PartialViewResult MenuNav(int entityInfoId = 0)
        {

            IEnumerable<MenuNavModel> models = instanceService.Get(t => t
            .GroupBy(i => i.EntityInfo).OrderBy(g => g.Key.Name).Select(g => new MenuNavModel{ EntityInfo = g.Key, Count = g.Select(i => i.GroupID).Distinct().Count() })
            );

            return PartialView(models);
        }

        #region ////////////////////////////AJAX
        public PartialViewResult InstanceRecCollection(int instanceId)
        {
            InstanceModel instance = instanceService.GetById(instanceId);
            IEnumerable<InstanceModel> oldInstances = instanceService.Get(T=>T
                .Where(i => i.GroupID == instance.GroupID && i.Id != instanceId)
                .OrderByDescending(i => i.Id)
            );

            return PartialView(oldInstances);
        }

        public PartialViewResult InstanceRecTooltip(int instanceId)
        {
            InstanceModel instance = instanceService.GetById(instanceId);

            return PartialView(instance);
        }
        #endregion


        #region////////////////////////////Private metods
        /// <summary>
        /// Редактирование стратегии
        /// </summary>
        /// <param name="instanceId">Если 0 - создание нвого варианта</param>
        /// <returns></returns>
        private ViewResult _Edit(InstanceModelUI model)
        {
            InitializeLists();
            LoadNavigationProperties(model);

            return View("Edit", model);

        }

        private void InitializeLists()
        {
            ViewBag.TickerList = ModelHelper.GetTickerList(tickerRepository);
            ViewBag.TimeFrameList = ModelHelper.GetTimeFrameList(timeFrameRepository);
            ViewBag.StrategyInfoList = ModelHelper.GetStrategyInfoList(entityInfoRepository);

        }

        private void LoadNavigationProperties(InstanceModelUI model)
        {
            if (model.EntityInfo == null && model.EntityInfoId != 0)
                model.EntityInfo = entityInfoRepository.GetById(model.EntityInfoId);

            if (model.Ticker == null && model.TickerId != 0)
                model.Ticker = tickerRepository.GetById(model.TickerId);

            if (model.TimeFrame == null && model.TimeFrameId != 0)
                model.TimeFrame = timeFrameRepository.GetById(model.TimeFrameId);

        }

        /// <summary>
        /// добавить несохраненные параметры
        /// </summary>
        /// <param name="model"></param>
        private void RepairParams(InstanceModel model)
        {
            IStrategy strategy = resolver.Resolve<IStrategy>(Type.GetType(model.EntityInfo.TypeName));
            new SettingHelper().RepairValues(strategy, model.EntityParams);
        }

        #endregion

    }
}

RMarket.WebUI/Views/Instance/Details.cshtml
@using RMarket.WebUI.Models;

@model InstanceModelUI

@{
    ViewBag.Title = "Просмотр селекции";
}


<div class="panel">
    <div class="panel-heading">
        <h3>Просмотр стратегии: <span class="text-info">@Model.Name</span></h3>
    </div>
   
        <div class="form-group">
            <table>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Name)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.EntityInfoId)
                    </td>
                    <td>
                         @Html.DisplayFor(m => m.EntityInfo.Name)
                    </td>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.TickerId)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Ticker.Code)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.TimeFrameId)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.TimeFrame.Name)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Balance)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Balance)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Slippage)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Slippage)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Rent)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Rent)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.Description)
                    </td>
                </tr>
            </table>
        </div>

        @Html.Partial("~/Views/EntityParams/EditParams.cshtml", Model.EntityParams)

        <div class="panel-footer">
            @Html.ActionLink("Назад", "Index", null, new { @class = "btn btn-default" })
        </div>

</div>




RMarket.WebUI/Views/Instance/Edit.cshtml
@using RMarket.WebUI.Models;

@model InstanceModelUI

@*<script src="~/Scripts/jquery-2.1.4.min.js"></script>*@

<script>
    $(function () {
        $("#EntityInfoId").change(function () {
            $("#ajaxStrategyParams").load("@Url.Action("EditParamsNew","EntityParams")?entityInfoId=" + this.value) 
        });

    });
</script>

@{
    ViewBag.Title = "Редактирование стратегии";
}

@{
    bool isCreate = Model.Id == 0 ? true : false;
    object attr;
    if (isCreate)
    {
        attr = new
        {
            @class = "form-control",
        };
    }
    else
    {
        attr = new
        {
            @class = "form-control",
            @readonly = "readonly",
        };

    }
}

    <div class="panel-heading">
        <h3>Редактирование стратегии: <span class="text-info">@Model.Name</span></h3>
    </div>

    @using (Html.BeginForm("Edit","Instance", FormMethod.Post, new {@class= "form-horizontal", role = "form" }))
    {
        @Html.ValidationSummary()

        <input id="Id" name="Id" type="text" value=@Model.Id style="display:none">
        @Html.HiddenFor(m => m.GroupID)

        <fieldset>
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Name, attr)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.EntityInfoId, new { @class = "col-sm-2" })
                <div class="col-sm-10">
                    @if (isCreate)
                {
                        @Html.DropDownListFor(m => m.EntityInfoId, ViewBag.StrategyInfoList as IEnumerable<SelectListItem>, "--SELECT--", attr)
                    }
                    else
                    {
                        @Html.TextBoxFor(m => m.EntityInfo.Name, attr);
                        @Html.HiddenFor(m => m.EntityInfoId)
                    }
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.TickerId, new { @class = "col-sm-2" })
                <div class="col-sm-10">
                    @if (isCreate)
                {
                        @Html.DropDownListFor(m => m.TickerId, ViewBag.TickerList as IEnumerable<SelectListItem>, "--SELECT--", attr)
                    }
                    else
                    {
                        @Html.TextBoxFor(m => m.Ticker.Code, attr)
                        @Html.HiddenFor(m => m.TickerId);
                }
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.TimeFrameId, new { @class = "col-sm-2" })
                <div class="col-sm-10">
                    @if (isCreate)
                {
                        @Html.DropDownListFor(m => m.TimeFrameId, ViewBag.TimeFrameList as IEnumerable<SelectListItem>, "--SELECT--", attr)
                    }
                    else
                    {
                        @Html.TextBoxFor(m => m.TimeFrame.Name, attr)
                        @Html.HiddenFor(m => m.TimeFrameId);
                }
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Balance, new { @class = "col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Balance, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Slippage, new { @class = "col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Slippage, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Rent, new { @class = "col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.Rent, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Description, new { @class = "col-sm-2" })
                <div class="col-sm-10">
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                </div>
            </div>
        </fieldset>

        <div id="ajaxStrategyParams">
            @Html.Partial("~/Views/EntityParams/EditParams.cshtml", Model.EntityParams)
        </div>

        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить", "Index", null, new { @class = "btn btn-default" })
        </div>
        }

RMarket.WebUI/Views/Instance/Index.cshtml
@using RMarket.ClassLib.EntityModels;

@model IEnumerable<InstanceModel>

<style>

</style>

<script>
    $(function () {
        $(".oldVersionLink").click(function () {
            loadOldInstances(this);
        });

        $('[data-toggle="tooltip"]').mouseenter(function () {
            initTooltip(this);
        });
        
    })

    function loadOldInstances(elem) {
        if ($(elem).attr("data-needLoad") == 0)
            return;

        var instanceId = $(elem).attr("data-instanceId");
        $("#ajaxOldInstances_" + instanceId).load("@Url.Action("InstanceRecCollection")", { instanceId: instanceId },
       function (response, status, xhr) {
           $(elem).attr("data-needLoad", 0);
           $('[data-toggle="tooltip"]', $(this)).mouseenter(function () {
               initTooltip(this);
           });
       });
    }

    function initTooltip(elem) {
        if ($(elem).attr("data-original-title") != undefined)
            return;
        var instanceId = $(elem).attr("data-instanceId");
        $.get("@Url.Action("InstanceRecTooltip")", { instanceId: instanceId },
            function (data) {
                $(elem).attr("data-original-title", data);
                $(elem).tooltip({ html: true });
                $(elem).tooltip("show");
            });
    }

</script>

@{
    ViewBag.Title = "Экземпляры стратегий";
}
<div class="row panel">
    <div class="col-sm-2 hidden-xs">
        @Html.Action("MenuNav")
    </div>
    <div class="col-xs-12 col-sm-10">
        @Html.ActionLink("Создать", "Edit", null, new { @class = "btn" })
        @foreach (InstanceModel m in @Model)
        {
            <div class="well">
                <div class="row">
                    <div class="col-xs-10">
                        <div class="list-group">
                            @Html.Partial("InstanceRec", m)
                            <a href="#ajaxOldInstances_@m.Id" class="oldVersionLink" data-toggle="collapse" data-needLoad="1" data-instanceId="@m.Id">Предыдущие версии</a>
                            <div id="ajaxOldInstances_@m.Id" class="collapse">
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <div class="list-group pull-right">
                            @Html.ActionLink("Изменить", "Edit", new {id = m.Id }, new { @class = "list-group-item" })
                            @Html.ActionLink("Копировать", "Copy", new { id = m.Id }, new { @class = "list-group-item" })
                        </div>
                    </div>

                </div>
            </div>
        }
    </div>
</div>

RMarket.WebUI/Views/Instance/InstanceRec.cshtml
@using RMarket.ClassLib.EntityModels;

@model InstanceModel

<a class="list-group-item" href="@Url.Action("Details", new { id = Model.Id })" data-instanceId="@Model.Id" data-toggle="tooltip" data-placement="bottom">
    <strong class="h3">@Model.Name</strong>
    <time>@Model.CreateDate</time>
</a>

RMarket.WebUI/Views/Instance/InstanceRecCollection.cshtml
@using RMarket.ClassLib.EntityModels

@model IEnumerable<InstanceModel>

@foreach (InstanceModel m in Model)
{
    @Html.Partial("InstanceRec", m)
}

RMarket.WebUI/Views/Instance/InstanceRecTooltip.cshtml
@using RMarket.ClassLib.EntityModels;

@model InstanceModel

<div>
    <p>@Model.Description</p>
    <p>@Model.CreateDate</p>
</div>