RMarket.WebUI/Controllers/EmulController.cs
using Newtonsoft.Json;
using RMarket.ClassLib.Abstract;
using RMarket.ClassLib.Abstract.IRepository;
using RMarket.ClassLib.Abstract.IService;
using RMarket.ClassLib.Entities;
using RMarket.ClassLib.EntityModels;
using RMarket.ClassLib.Helpers;
using RMarket.ClassLib.Infrastructure.AmbientContext;
using RMarket.ClassLib.Managers;
using RMarket.ClassLib.Models;
using RMarket.WebUI.Helpers;
using RMarket.WebUI.Infrastructure;
using RMarket.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace RMarket.WebUI.Controllers
{
    public class EmulController : Controller
    {
        private readonly IInstanceService instanceService;
        private readonly IDataProviderSettingService dataProviderService;
        private readonly IAliveStrategyRepository aliveStrategyRepository;
        private readonly IOrderRepository orderRepository;
        private readonly IResolver resolver;

        private JsonSerializerSettings jsonSerializerSettings;


        List<AliveResult> strategyResultCollection = CurrentUI.AliveResults;

        public EmulController(IInstanceService instanceService, 
            IDataProviderSettingService dataProviderService, 
            IAliveStrategyRepository aliveStrategyRepository, 
            IOrderRepository orderRepository,
            IResolver resolver)
        {
            this.instanceService = instanceService;
            this.dataProviderService = dataProviderService;
            this.aliveStrategyRepository = aliveStrategyRepository;
            this.orderRepository = orderRepository;
            this.resolver = resolver;

            jsonSerializerSettings = new JsonSerializerSettings();
            jsonSerializerSettings.NullValueHandling = NullValueHandling.Ignore;

        }

        // GET:
        public ActionResult Index()
        {
            //определить наличия работающего теста и вызвать форму нового, или результата
            if (strategyResultCollection.Count == 0)
            {
                DateTime dateFrom = DateTime.Now.Date.AddMonths(-1);
                DateTime dateTo = DateTime.Now.Date;
                return RedirectToAction("BeginTest", new { instanceId = 0, dateFrom = dateFrom, dateTo = dateTo });
            }
            else
            {
                return View(strategyResultCollection);
            }
        }

        [HttpGet]
        public ViewResult BeginTest()
        {
            ViewBag.InstanceList = ModelHelper.GetInstanceList(instanceService);
            ViewBag.SettingList = ModelHelper.GetDataProviderSettingList(dataProviderService);

            DateTime dateFrom = DateTime.Now.Date.AddMonths(-1);
            DateTime dateTo = DateTime.Now.Date;

            TesterModel model = new TesterModel();
            model.DateFrom = dateFrom;
            model.DateTo = dateTo;

            return View(model);
        }

        [HttpPost]
        public ActionResult BeginTest(TesterModel model) 
        {
            if (ModelState.IsValid)
            {
                InstanceModel instance = instanceService.GetById(model.InstanceId, true);
                DataProviderSettingModel setting = dataProviderService.GetById(model.SettingId);

                //добавляем живую стратегию
                AliveStrategy aliveStrategy = new AliveStrategy
                {
                    GroupID = instance.GroupID,
                    IsActive = true
                };
                aliveStrategyRepository.Save(aliveStrategy);

                //получаем стратегию 
                IStrategy strategy = new SettingHelper().CreateEntityObject<IStrategy>(instance, resolver);

                //устанавливаем остальные свойства
                Instrument instr = new Instrument(instance.Ticker, instance.TimeFrame);

                Portfolio portf = new Portfolio
                {
                    Balance = instance.Balance,
                    Rent = instance.Rent,
                    Slippage = instance.Slippage
                };

                IDataProvider dataProvider = new SettingHelper().CreateEntityObject<IDataProvider>(setting, resolver);

                IManager manager = new EmulManager(orderRepository, strategy, instr, portf, dataProvider, aliveStrategy);

                //manager.DateFrom = model.DateFrom;
                //manager.DateTo = model.DateTo;

                //Стартуем стратегию
                manager.StartStrategy();

                //***Положить в сессию
                AliveResult aliveResult = new AliveResult
                {
                    AliveId = aliveStrategy.Id,
                    StartDate = DateTime.Now,
                    Instance = instance,
                    Strategy = strategy,
                    Manager = manager
                };

                //Извлечь индикаторы из  объекта стратегии
                aliveResult.IndicatorsDict = StrategyHelper.ExtractIndicatorsInStrategy(strategy);

                strategyResultCollection.Add(aliveResult);
                //**

                TempData["message"] = string.Format("Эмуляция успешно запущена. Id={0}", aliveResult.AliveId);

                return RedirectToAction("Index");
            }

            ViewBag.InstanceList = ModelHelper.GetInstanceList(instanceService);

            return View(model);
        }

        [HttpGet]
        public ActionResult DisplayResult(int aliveId)
        {
            AliveResult aliveResult = strategyResultCollection.FirstOrDefault(t => t.AliveId == aliveId);
            if (aliveResult == null)
            {
                TempData["error"] = string.Format("Не найдена эмуляция Id:{0}", aliveId);
                return RedirectToAction("Index");
            }

            //if (aliveResult.Strategy.Instr.Candles.Count == 0)
            //{
            //    TempData["error"] = string.Format("Нет сформированных свечей за выбранный период Id:{0}", aliveId);
            //    return RedirectToAction("Index");
            //}

            return View(aliveResult);

        }

        [HttpGet]
        public RedirectToRouteResult TerminateTest(int aliveId)
        {
            AliveResult aliveResult = strategyResultCollection.FirstOrDefault(t => t.AliveId == aliveId);
            if (aliveResult != null && aliveResult.Manager.IsStarted)
            {
                aliveResult.Manager.StopStrategy();
                TempData["warning"] = string.Format("Эмуляция Id={0} была прервана!", aliveResult.AliveId);
            }

            return RedirectToAction("DisplayResult", new { aliveId = aliveResult.AliveId });
        }


        #region //////////////////////Навигация по графику
        /// <summary>
        /// Загрузка последних n свечек
        /// </summary>
        /// <param name="aliveId"></param>
        /// <param name="maxCount"></param>
        /// <returns></returns>
        public ActionResult GetDataJsonInit(int aliveId, int maxCount, string way = "right")
        {
            AliveResult aliveResult = strategyResultCollection.FirstOrDefault(t => t.AliveId == aliveId);

            AliveResultHelperUI helper = new AliveResultHelperUI(aliveResult);
            var res = helper.GetDataJsonInit(maxCount, way);

            return new JsonNetResult(res, JsonRequestBehavior.AllowGet, jsonSerializerSettings);
        }

        /// <summary>
        /// загрузка свечей после определенной даты вперед-назад
        /// </summary>
        /// <param name="aliveId"></param>
        /// <param name="lastDateUTC"></param>
        /// <param name="maxCount"></param>
        /// /// <param name="way">right, left</param>
        /// <returns></returns>
        public ActionResult GetDataJsonSlice(int aliveId, double lastDateUTC, int maxCount, string way = "right")
        {
            DateTime posixTime = DateTime.SpecifyKind(new DateTime(1970, 1, 1), DateTimeKind.Utc);
            DateTime lastDate = posixTime.AddMilliseconds(lastDateUTC);

            AliveResult aliveResult = strategyResultCollection.FirstOrDefault(t => t.AliveId == aliveId);
            if (aliveResult == null)
            {
                TempData["error"] = string.Format("Не найден тест Id={0}", aliveResult.AliveId);
                return RedirectToAction("Index");
            }

            AliveResultHelperUI helper = new AliveResultHelperUI(aliveResult);
            var res = helper.GetDataJsonSlice(lastDate, maxCount, way);

            return new JsonNetResult(res, JsonRequestBehavior.AllowGet, jsonSerializerSettings);
        }

        /// <summary>
        /// подгрузка свечей через интервал
        /// </summary>
        /// <param name="aliveId"></param>
        /// <param name="lastDateUTC"></param>
        /// <param name="maxCount"></param>
        /// <returns></returns>
        public ActionResult GetDataJsonAdd(int aliveId, double lastDateUTC, int maxCount)
        {
            DateTime posixTime = DateTime.SpecifyKind(new DateTime(1970, 1, 1), DateTimeKind.Utc);
            DateTime lastDate = posixTime.AddMilliseconds(lastDateUTC);

            AliveResult aliveResult = strategyResultCollection.FirstOrDefault(t => t.AliveId == aliveId);
            if (aliveResult == null)
            {
                TempData["error"] = string.Format("Не найден тест Id={0}", aliveResult.AliveId);
                return RedirectToAction("Index");
            }

            AliveResultHelperUI helper = new AliveResultHelperUI(aliveResult);
            var res = helper.GetDataJsonAdd(lastDate, maxCount);

            return new JsonNetResult(res, JsonRequestBehavior.AllowGet, jsonSerializerSettings);
        }
        #endregion
    }
}

RMarket.WebUI/Controllers/InstanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using RMarket.ClassLib.Abstract;
using RMarket.ClassLib.Entities;
using RMarket.ClassLib.Models;
using RMarket.WebUI.Infrastructure;
using RMarket.ClassLib.Helpers;
using RMarket.WebUI.Models;
using RMarket.ClassLib.EntityModels;
using RMarket.ClassLib.Abstract.IService;
using RMarket.ClassLib.Abstract.IRepository;
using RMarket.ClassLib.Infrastructure.AmbientContext;

namespace RMarket.WebUI.Controllers
{
    public class InstanceController : Controller
    {
        private IInstanceService instanceService;
        private ITickerRepository tickerRepository;
        private ITimeFrameRepository timeFrameRepository;
        private IEntityInfoRepository entityInfoRepository;
        private readonly IResolver resolver;

        public MyMapper Mapper { get; set; }

        public InstanceController(IInstanceService instanceService, ITickerRepository tickerRepository, ITimeFrameRepository timeFrameRepository, IEntityInfoRepository entityInfoRepository, IResolver resolver)
        {
            this.instanceService = instanceService;
            this.tickerRepository = tickerRepository;
            this.timeFrameRepository = timeFrameRepository;
            this.entityInfoRepository = entityInfoRepository;
            this.resolver = resolver;
        }

        /// <summary>
        /// Список вариантов стратегий
        /// </summary>
        /// <returns></returns>
        public ViewResult Index(int entityInfoId = 0)
        {
            IEnumerable<InstanceModel> res = instanceService.Get(T => T
                .Where(i => i.EntityInfoId == entityInfoId || entityInfoId == 0)
                .GroupBy(s => s.GroupID)
                .SelectMany(g => g.Select(s => s)
                    .OrderByDescending(s => s.Id)
                    .Take(1)
                ).Include(m => m.EntityInfo)
            );

            return View(res);

        }

        /// <summary>
        /// Редактирование стратегии
        /// </summary>
        /// <param name="id">Если 0 - создание нвого варианта</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Edit(int id = 0)
        {
            InitializeLists();
            InstanceModel model = null;

            if (id != 0)
            {
                model = instanceService.GetById(id, true);
                if (model == null)
                {
                    TempData["error"] = String.Format("Экземпляр стратегии \"{0}\"  не найден!", id);
                    return RedirectToAction("Index");
                }
                RepairParams(model);
            }
            else 
                model = new InstanceModel();

            InstanceModelUI modelUI = Mapper
                .Map<InstanceModel, InstanceModelUI>(model);

            return View("Edit", modelUI);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(InstanceModelUI modelUI, IEnumerable<ParamEntityUI> strategyParams)
        {
            modelUI.EntityParams = strategyParams.ToList();

            if (ModelState.IsValid)
            {
                //Сохранение
                InstanceModel model = Mapper
                    .Map<InstanceModelUI, InstanceModel>(modelUI);

                instanceService.Save(model);

                TempData["message"] = String.Format("Сохранены изменения в экземпляре: {0}", model.Name);
                return RedirectToAction("Index");
            }

            else
            {
                return _Edit(modelUI);
            }

        }

        [HttpGet]
        public ActionResult Copy(int id)
        {
            InstanceModel model = instanceService.GetById(id, true);
            if (model == null)
            {
                TempData["error"] = String.Format("Экземпляр стратегии \"{0}\"  не найден!", id);
                return RedirectToAction("Index");
            }
            RepairParams(model);

            model.Id = 0;

            InstanceModelUI modelUI = Mapper
                .Map<InstanceModel, InstanceModelUI>(model);

            return _Edit(modelUI);
        }

        public ActionResult Details(int id)
        {
            InstanceModel model = new InstanceModel();
            if (id != 0)
            {
                model = instanceService.GetById(id, true);
                if (model == null)
                {
                    TempData["error"] = String.Format("Экземпляр стратегии \"{0}\"  не найден!", id);
                    return RedirectToAction("Index");
                }
                RepairParams(model);
            }

            InstanceModelUI modelUI = Mapper
                .Map<InstanceModel, InstanceModelUI>(model);

            return View(modelUI);
        }

        public PartialViewResult MenuNav(int entityInfoId = 0)
        {

            IEnumerable<MenuNavModel> models = instanceService.Get(t => t
            .GroupBy(i => i.EntityInfo).OrderBy(g => g.Key.Name).Select(g => new MenuNavModel{ EntityInfo = g.Key, Count = g.Select(i => i.GroupID).Distinct().Count() })
            );

            return PartialView(models);
        }

        #region ////////////////////////////AJAX
        public PartialViewResult InstanceRecCollection(int instanceId)
        {
            InstanceModel instance = instanceService.GetById(instanceId);
            IEnumerable<InstanceModel> oldInstances = instanceService.Get(T=>T
                .Where(i => i.GroupID == instance.GroupID && i.Id != instanceId)
                .OrderByDescending(i => i.Id)
            );

            return PartialView(oldInstances);
        }

        public PartialViewResult InstanceRecTooltip(int instanceId)
        {
            InstanceModel instance = instanceService.GetById(instanceId);

            return PartialView(instance);
        }
        #endregion


        #region////////////////////////////Private metods
        /// <summary>
        /// Редактирование стратегии
        /// </summary>
        /// <param name="instanceId">Если 0 - создание нвого варианта</param>
        /// <returns></returns>
        private ViewResult _Edit(InstanceModelUI model)
        {
            InitializeLists();
            LoadNavigationProperties(model);

            return View("Edit", model);

        }

        private void InitializeLists()
        {
            ViewBag.TickerList = ModelHelper.GetTickerList(tickerRepository);
            ViewBag.TimeFrameList = ModelHelper.GetTimeFrameList(timeFrameRepository);
            ViewBag.StrategyInfoList = ModelHelper.GetStrategyInfoList(entityInfoRepository);

        }

        private void LoadNavigationProperties(InstanceModelUI model)
        {
            if (model.EntityInfo == null && model.EntityInfoId != 0)
                model.EntityInfo = entityInfoRepository.GetById(model.EntityInfoId);

            if (model.Ticker == null && model.TickerId != 0)
                model.Ticker = tickerRepository.GetById(model.TickerId);

            if (model.TimeFrame == null && model.TimeFrameId != 0)
                model.TimeFrame = timeFrameRepository.GetById(model.TimeFrameId);

        }

        /// <summary>
        /// добавить несохраненные параметры
        /// </summary>
        /// <param name="model"></param>
        private void RepairParams(InstanceModel model)
        {
            IStrategy strategy = resolver.Resolve<IStrategy>(Type.GetType(model.EntityInfo.TypeName));
            new SettingHelper().RepairValues(strategy, model.EntityParams);
        }

        #endregion

    }
}

RMarket.WebUI/Views/Shared/DisplayResult.cshtml
@model RMarket.ClassLib.Models.AliveResult

<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="~/Scripts/highstock/highstock.js"></script>

<script src="/Scripts/jquery.signalR-2.2.0.min.js"></script>
<!--Ссылка на автоматически сгенерированный скрипт хаба SignalR -->
<script src="/signalr/hubs"></script>


<style>
    #chart{
        height:700px;
    }
</style>

<script>
    var lastDate = 0;
    var maxCount = 400;
    var timeout = @Model.Strategy.Instr.TimeFrame.ToMinute * 60 * 1000;

    var min;
    var max;
    var userMin;
    var userMax;

    var chart;

    $(function () {

        InitiateChart();
        var url = "@{@Url.Action("GetDataJsonInit")}?aliveId=@Model.AliveId&maxCount=" + maxCount+"&way=right";
        GetDataInit(chart, url);


        $("#btnLeftSkip").click(function(){
            UpdateVariable();
            InitiateChart();
            var url = "@{@Url.Action("GetDataJsonInit")}?aliveId=@Model.AliveId&maxCount=" + maxCount+"&way=left";
            GetDataInit(chart, url);
        });

        $("#btnRightSkip").click(function(){
            UpdateVariable();
            InitiateChart();
            var url = "@{@Url.Action("GetDataJsonInit")}?aliveId=@Model.AliveId&maxCount=" + maxCount+"&way=right";
            GetDataInit(chart, url);
        });

        $("#btnLeftFast").click(function(){
            UpdateVariable();
            InitiateChart();
            var url = "@{@Url.Action("GetDataJsonSlice")}?aliveId=@Model.AliveId&lastDateUTC="+min+"&maxCount=" + maxCount+"&way=left";
            GetDataInit(chart, url);
        });

        $("#btnRightFast").click(function(){
            UpdateVariable();
            InitiateChart();
            var url = "@{@Url.Action("GetDataJsonSlice")}?aliveId=@Model.AliveId&lastDateUTC="+max+"&maxCount=" + maxCount+"&way=right";
            GetDataInit(chart, url);
        });

        $("#btnLeft").click(function(){
            UpdateVariable();
            var _data = chart.series[0].data;
            var _maxCount =  maxCount>>1;
            var _lastDate = min;
            if(_data.length > _maxCount)
                _lastDate = _data[_maxCount-1].x;
            InitiateChart();
            var url = "@{@Url.Action("GetDataJsonSlice")}?aliveId=@Model.AliveId&lastDateUTC="+_lastDate+"&maxCount=" + maxCount+"&way=left";
            GetDataInit(chart, url);
        });

        $("#btnRight").click(function(){
            UpdateVariable();
            var _data = chart.series[0].data;
            var _maxCount =  maxCount>>1;
            var _lastDate = max;
            if(_data.length > _maxCount)
                _lastDate = _data[_data.length-_maxCount-1].x;
            InitiateChart();
            var url = "@{@Url.Action("GetDataJsonSlice")}?aliveId=@Model.AliveId&lastDateUTC="+_lastDate+"&maxCount=" + maxCount+"&way=right";
            GetDataInit(chart, url);
        });

        //***SignalR
        var hub = $.connection.notificationHub;
        // Открываем соединение
        $.connection.hub.start().done(function () {           
            hub.server.connect(@Model.AliveId);
        });

        hub.client.candleCreated = function(param){
            //свеча сформирована
            $("#btnRightSkip").click();
        }
        //**

    });

    // create the chart
    function InitiateChart(){

        $('#chart').highcharts('StockChart', {
            xAxis: {
                minRange: timeout
            },
            rangeSelector: {
                buttons: [{
                    type: 'hour',count: 1,text: '1h'
                }, {
                    type: 'day',count: 1,text: '1d'
                }, {
                    type: 'month',count: 1,text: '1m'
                }, {
                    type: 'year',count: 1,text: '1y'
                }, {
                    type: 'all',text: 'All'
                }],
                selected: 4
            },
            title: {
                text: 'Результат'
            },
            yAxis: [{
                title: {
                    text: 'OHLC'
                },
                height: '68%',
                lineWidth: 2
            }, {
                title: {
                    text: 'Balance'
                },
                top: '70%',
                height: '30%',
                offset: 0,
                lineWidth: 2
            }],
            series: [{
                type: 'ohlc',
                name: 'OHLC',
                dataGrouping: {
                    enabled: false},
            },
            {
                type: 'line',
                name: 'Balance',
                yAxis: 1,
                dataGrouping: {
                    enabled: false
                }
            },
            ]
        });

        chart = $('#chart').highcharts();
    }

    function UpdateVariable(){
        //save old user values
        min = chart.xAxis[0].dataMin;
        max = chart.xAxis[0].dataMax;
        userMin = chart.xAxis[0].userMin;
        userMax = chart.xAxis[0].userMax;

    };

    function GetDataInit(chart,url) {
        $.getJSON(url,
        function (data) {
            if (data != null) {
                chart.series[0].update({
                    data:data.Candles
                },false);
                chart.series[1].update(
                    data.Orders
                ,false);
                for(var i = 0; i<data.Indicators.length; i++){
                    chart.addSeries(
                   data.Indicators[i]
                ,false,false);
                }
                for(var i = 0; i<data.ProfitList.length; i++){
                    chart.addSeries(
                   data.ProfitList[i]
                ,false,false);
                }
                chart.redraw(false);
                //запускаем подгрузку свечей
                if(data.Status==1)
                    setTimeout(AddPoint(chart), timeout);

                HideNavigateButton(data.Status);
            }
        });
    };

    function AddPoint(chart) {
        return; //доделать для реалтайм
        var series = chart.series[0];
        $.getJSON("@{@Url.Action("GetDataJsonAdd")}?aliveId=@Model.AliveId&lastDateUTC="+lastDate+"&maxCount=" + maxCount,
        function (data) {
            //alert(data);
            if (data != null) {
                var candleList = data.Candles;
                for (var i = 0; i < candleList.length; i++) {
                    series.addPoint(candleList[i], false);
                }
                chart.redraw();
                lastDate = dataList[candleList.length - 1][0];

                if(data.Status==1)
                    setTimeout(AddPoint(chart), timeout);
            }
        });
    };

    function HideNavigateButton(status)
    {
        var _displayLeft = "";
        var _displayRight = "";

        if(status==3)
            _displayLeft = "none";
        else if(status == 1 || status == 2)
            _displayRight = "none";

        $("#btnRight").css("display",_displayRight);
        $("#btnRightFast").css("display",_displayRight);
        $("#btnRightSkip").css("display",_displayRight);
        $("#btnLeftSkip").css("display",_displayLeft);
        $("#btnLeftFast").css("display",_displayLeft);
        $("#btnLeft").css("display",_displayLeft);
    }

</script>


@{
    ViewBag.Title = "DisplayResult";
}

<h2>DisplayResult</h2>

<div id="chart"></div>
<div class="container">
    <button id="btnLeftSkip">
        <img src="~/Content/Img/1441930899_ic_skip_previous_48px.png" />
    </button>
    <button id="btnLeftFast">
        <img src="~/Content/Img/1441852748_ic_fast_rewind_48px.png" />
    </button>
    <button id="btnLeft">
        <img src="~/Content/Img/1441852585_ic_keyboard_arrow_left_48px.png" />
    </button>

    <button id="btnRightSkip" class="pull-right">
        <img src="~/Content/Img/1441930718_ic_skip_next_48px.png" />
    </button>
    <button id="btnRightFast" class="pull-right">
        <img src="~/Content/Img/1441852769_ic_fast_forward_48px.png" />
    </button>
    <button id="btnRight" class="pull-right">
        <img class="pull-right" src="~/Content/Img/1441852569_ic_keyboard_arrow_right_48px.png" />
    </button>
</div>
<div id="balanceChart"></div>

RMarket.WebUI/Views/Shared/EditParams.cshtml
@using RMarket.WebUI.Models;
@model List<ParamEntityUI>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Name")
            </th>
            <th>
                @Html.DisplayName("Value")
            </th>
            <th>
                @Html.DisplayName("Description")
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count(); i++)
        {
            <tr>
                <td>
                    <label for="[@i].FieldValue"> @Model[i].DisplayName</label>
                    @Html.HiddenFor(m => m[i].FieldName)
                    @Html.HiddenFor(m => m[i].DisplayName)
                </td>
                <td>
                    @Html.Partial("EditorForObject", new KeyValuePair<string, ParamEntityUI>($"[{i}].FieldValue", Model[i]))
                    @*@Html.EditorFor(m=>m[i].FieldValue)*@
                </td>
                <td>
                    @Model[i].Description
                    @Html.HiddenFor(m => m[i].Description)
                    @Html.HiddenFor(m => m[i].TypeName)
                </td>
            </tr>
        }
    </tbody>
</table>

RMarket.WebUI/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryvalidate")
    @Scripts.Render("~/bundles/jqueryunobtrusiveajax")

    <link href="~/Content/themes/base/all.css" rel="stylesheet" type="text/css" />

    <style>
        .btn .caret, .cstm-text{
        margin-left: 4px;
        }

    </style>

</head>
<body>
    <div class="container navbar-inverse" role="navigation">
        <div class="row">
            <div class="btn-toolbar" role="toolbar">
                @Html.ActionLink("Мои стратегии","Index", "Instance",null, new { @class = "btn btn-default btn-success" })
                @Html.ActionLink("загрузка истории", "Index", "DownloadHistory", null, new { @class = "btn btn-default" })
                @Html.ActionLink("Тестирование", "Index", "Tester", null, new { @class = "btn btn-default" })
                @Html.ActionLink("Эмуляция", "Index", "Emul", null, new { @class = "btn btn-default" })
                @Html.ActionLink("Селекции", "Index", "Selection", null, new { @class = "btn btn-default" })

                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Справочники<span class="caret"></span></button>
                    <ul class="dropdown-menu dropdown-menu-right" role="menu">
                        <li class="text-right">@Html.ActionLink("Entity info", "Index", "EntityInfoes")</li>
                        <li class="text-right">@Html.ActionLink("Инструменты", "Index", "Tickers")</li>
                        <li class="text-right">@Html.ActionLink("Интервалы", "Index", "TimeFrames")</li>
                    </ul>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Настройки<span class="glyphicon glyphicon-cog"></span></button>
                    <ul class="dropdown-menu dropdown-menu-right" role="menu">
                        <li class="text-right">@Html.ActionLink("Data prividers", "Index", "DataProviderSettings")</li>
                        <li class="text-right">@Html.ActionLink("Histrical providers", "Index", "HistoricalProviderSettings")</li>
                        <li class="text-right">@Html.ActionLink("Optimization", "Index", "OptimizationSettings")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                @TempData["message"]
            </div>
        }
        @if (TempData["error"] != null)
        {
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                @TempData["error"]
            </div>
        }
        @if (TempData["warning"] != null)
        {
            <div class="alert alert-warning alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                @TempData["warning"]
            </div>
        }


        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

</body>
</html>