RMarket.WebUI/Controllers/EntityParamsController.cs
using RMarket.ClassLib.Abstract;
using RMarket.ClassLib.Abstract.IRepository;
using RMarket.ClassLib.Entities;
using RMarket.ClassLib.Helpers;
using RMarket.ClassLib.Helpers.Extentions;
using RMarket.ClassLib.Infrastructure.AmbientContext;
using RMarket.ClassLib.Models;
using RMarket.WebUI.Models;
using RMarket.WebUI.Models.ParamforEdit;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMarket.WebUI.Controllers
{
    public class EntityParamsController : Controller
    {
        private readonly IEntityInfoRepository entityInfoRepository;
        private readonly IResolver resolver;

        public MyMapper Mapper { get; set; }

        public EntityParamsController(IEntityInfoRepository entityInfoRepository, IResolver resolver)
        {
            this.entityInfoRepository = entityInfoRepository;
            this.resolver = resolver;
        }

        //Новый экземпляр
        public PartialViewResult EditParamsNew(int entityInfoId)
        {
            EntityInfo entityInfo = entityInfoRepository.GetById(entityInfoId);
            object entity = resolver.Resolve<object>(Type.GetType(entityInfo.TypeName));
            IEnumerable<ParamEntity> entityParams = new SettingHelper().GetEntityParams<ParamEntity>(entity);

            //Конвертим параметры в UI модель
            IEnumerable<ParamEntityUI> entityParamsUI = Mapper
                .Map<IEnumerable<ParamEntity>, IEnumerable<ParamEntityUI>>(entityParams);

            return PartialView("EditParams", entityParamsUI);
        }

        /// <summary>
        /// Частичное представление выводит значение параметра с атрибутом ParameterAttribute
        /// </summary>
        /// <param name="paramEntityEdit">ключ - имя элемента</param>
        /// <returns></returns>
        public PartialViewResult EditorForObject(ParamEntityEditForObject paramEntityEdit)
        {
            // разные вью на разные типы значений
            object originValue = paramEntityEdit.ParamEntityUI.OriginValue;

            if (originValue is bool)
                return PartialView("EditorForBool", paramEntityEdit);
            else if (originValue is IEnumerable && !(originValue is string))
                return PartialView("EditorForCollection", paramEntityEdit);
            else if (originValue is Enum)
            {
                return EditForEnum(paramEntityEdit);
            }
            else
                return PartialView(paramEntityEdit);

        }

        public string GetDesctiptionForEnum(string enumValue, string typeName)
        {
            Type type = Type.GetType(typeName);
            var value = Enum.Parse(type, enumValue);
            return ((Enum)value).Description();
        }

        private PartialViewResult EditForEnum(ParamEntityEditForObject paramEntityEdit)
        {
            object originValue = paramEntityEdit.ParamEntityUI.OriginValue;

            var enumValues = Enum.GetValues(originValue.GetType());
            var enumValuesSelectList = new List<SelectListItem>();
            var listDescriptions = new List<SelectListItem>();
            foreach (var enumValue in enumValues)
            {
                enumValuesSelectList.Add(new SelectListItem
                {
                    Value = ((Enum)enumValue).ToString("F"),
                    Text = ((Enum)enumValue).Name(),
                    Selected = enumValue.ToString() == originValue.ToString()
                });

                listDescriptions.Add(new SelectListItem
                {
                    Value = ((Enum)enumValue).ToString("F"),
                    Text = ((Enum)enumValue).Description(),
                    Selected = enumValue == originValue
                });
            }

            var model = new ParamEntityUiForEnum
            {
                ControlId = paramEntityEdit.ControlId,
                ParamEntityUI = paramEntityEdit.ParamEntityUI,
                ValuesSelectList = enumValuesSelectList,
                //DescriptionCollection = listDescriptions
            };

            return PartialView("EditorForEnum", model);
        }
    }
}

RMarket.WebUI/Controllers/OptimizationSettingsController.cs
using RMarket.ClassLib.Abstract;
using RMarket.ClassLib.Abstract.IRepository;
using RMarket.ClassLib.Abstract.IService;
using RMarket.ClassLib.Entities;
using RMarket.ClassLib.EntityModels;
using RMarket.ClassLib.Helpers;
using RMarket.ClassLib.Infrastructure.AmbientContext;
using RMarket.ClassLib.Models;
using RMarket.WebUI.Infrastructure;
using RMarket.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RMarket.WebUI.Controllers
{
    public class OptimizationSettingsController : Controller
    {
        private IOptimizationSettingService settingService;
        private IEntityInfoRepository entityInfoRepository;
        private readonly IResolver resolver;

        public MyMapper Mapper { get; set; }

        public OptimizationSettingsController(IOptimizationSettingService settingService, IEntityInfoRepository entityInfoRepository, IResolver resolver)
        {
            this.settingService = settingService;
            this.entityInfoRepository = entityInfoRepository;
            this.resolver = resolver;
        }

        // GET: StrategySettings
        public ActionResult Index()
        {
            var res = settingService.Get().ToList();
            return View(res);
        }

        [HttpGet]
        public ActionResult Edit(int Id = 0)
        {
            InitializeLists();

            OptimizationSettingModel model = null;

            if (Id != 0)
            {
                model = settingService.GetById(Id, true);
                if (model == null)
                {
                    TempData["error"] = String.Format("Экземпляр настройки \"{0}\"  не найден!", Id);
                    return RedirectToAction("Index");
                }
                RepairParams(model);
            }
            else //Запрос на создание
                model = new OptimizationSettingModel();

            OptimizationSettingModelUI modelUI = Mapper
                .Map<OptimizationSettingModel, OptimizationSettingModelUI>(model);

            return View("Edit", modelUI);

        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(OptimizationSettingModelUI modelUI, IEnumerable<ParamEntityUI> entityParams)
        {
            modelUI.EntityParams = entityParams.ToList();

            if (ModelState.IsValid)
            {
                //Сохранение
                OptimizationSettingModel model = Mapper
                    .Map<OptimizationSettingModelUI, OptimizationSettingModel>(modelUI);

                settingService.Save(model);

                TempData["message"] = String.Format("Сохранены изменения в экземпляре: {0}", modelUI.Name);
                return RedirectToAction("Index");
            }

            else
            {
                return _Edit(model: modelUI);
            }
        }

        public ActionResult Copy(int Id)
        {
            OptimizationSettingModel model = settingService.GetById(Id, true);
            if (model == null)
            {
                TempData["error"] = String.Format("Экземпляр настройки \"{0}\"  не найден!", Id);
                return RedirectToAction("Index");
            }
            RepairParams(model);

            model.Id = 0;

            OptimizationSettingModelUI modelUI = Mapper
                .Map<OptimizationSettingModel, OptimizationSettingModelUI>(model);

            return _Edit(model: modelUI);
        }

        #region////////////////////////////Private metods

        private ActionResult _Edit(OptimizationSettingModelUI model)
        {
            InitializeLists();
            LoadNavigationProperties(model);

            return View("Edit", model);
        }

        private void InitializeLists()
        {
            ViewBag.EntityInfoList = ModelHelper.GetOptimizationInfoList(entityInfoRepository);
        }

        private void LoadNavigationProperties(OptimizationSettingModelUI model)
        {
            if (model.EntityInfo == null && model.EntityInfoId != 0)
                model.EntityInfo = entityInfoRepository.GetById(model.EntityInfoId);

        }

        /// <summary>
        /// добавить несохраненные параметры
        /// </summary>
        /// <param name="model"></param>
        private void RepairParams(OptimizationSettingModel model)
        {
            var entity = resolver.Resolve<IOptimization>(Type.GetType(model.EntityInfo.TypeName));
            new SettingHelper().RepairValues(entity, model.EntityParams);
        }


        #endregion


    }
}

RMarket.WebUI/Views/OptimizationSettings/Edit.cshtml
@using RMarket.WebUI.Models;

@model OptimizationSettingModelUI

<script>
    $(function () {
        $("#EntityInfoId").change(function () {
            $("#ajaxStrategyParams").load("@Url.Action("EditParamsNew","EntityParams")?entityInfoId=" + this.value)
        });

    });
</script>

@{
    ViewBag.Title = "OptimizationSetting";
}

<div class="panel">
    <div class="panel-heading">
        @if (Model.Id == 0)
        {
            <h3>Создание настройки</h3>
        }
        else
        {
            <h3>Редактирование настройки: <span class="text-info">@Model.Name</span></h3>
        }
    </div>

    @using (Html.BeginForm("Edit", "OptimizationSettings"))
    {
        @Html.ValidationSummary();

        <input id="Id" name="Id" type="text" value=@Model.Id style="display:none">

        <div class="form-group">
            <table>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Name)
                    </td>
                    <td>
                        @Html.TextBoxFor(m => m.Name, new {@class="form-control"})
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.EntityInfoId)
                    </td>
                    <td>
                        @Html.DropDownListFor(m => m.EntityInfoId, ViewBag.EntityInfoList as IEnumerable<SelectListItem>, "--SELECT--", new { @class = "form-control" })
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Description)
                    </td>
                    <td>
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                    </td>
                </tr>
            </table>
        </div>

        <div id="ajaxStrategyParams">
            @Html.Partial("~/Views/EntityParams/EditParams.cshtml", Model.EntityParams)
        </div>

        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить", "Index", null, new { @class = "btn btn-default" })
        </div>
    }

</div>






RMarket.WebUI/Views/OptimizationSettings/Index.cshtml
@using RMarket.ClassLib.EntityModels;

@model IEnumerable<OptimizationSettingModel>

@{
    ViewBag.Title = "OptimizationSettings";
}
@Html.ActionLink("Создать", "Edit", null, new { @class = "btn" })
@foreach (OptimizationSettingModel m in @Model)
{
    <div class="well">
        <div class="pull-right">
            @Html.ActionLink("Изменить", "Edit", new { Id = m.Id }, new { @class = "btn btn-default" })
            @Html.ActionLink("Копировать", "Copy", new { Id = m.Id }, new { @class = "btn btn-default" })
        </div>
        <strong class="h3">@m.Name</strong>
    </div>
}
